### ISSUE TITLE
/help/migration/ page linked in README upgrade instructions is missing 

### ISSUE THREAD

**Issue by berezovskyi** [KiCad/kicad-website#425] opened 2019-08-12 15:36 UTC
README.md from kicad-unified-5.1.2-1-10_14.dmg points to http://kicad-pcb.org/help/migration/ which does not resolve.

**Comment by nickoe** [comment] 2019-08-13 21:49
Duplicate of https://github.com/KiCad/kicad-website/issues/412

**Closed by nickoe** 2019-08-13 21:49 UTC
